# Generated by Django 3.1.3 on 2020-11-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20201130_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='answer',
            new_name='correct_answer',
        ),
    ]
