# Generated by Django 3.1.3 on 2020-12-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20201130_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option5',
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option1',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option2',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option3',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option4',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.TextField(max_length=500),
        ),
    ]
