# Generated by Django 3.1.3 on 2020-12-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20201201_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='option5',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
