# Generated by Django 3.1.3 on 2020-12-28 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quiz_option5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='option5',
        ),
    ]
