# Generated by Django 3.1.3 on 2020-12-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_remove_quiz_option5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option4',
            field=models.TextField(),
        ),
    ]
